### ISSUE TITLE
CascadeXML ausführen

### ISSUE THREAD

**Issue by leon-me** [FloHauss/XMC_HTC#4]
- siehe Anmerkungen von Ansgar:
---
schaut mal hier
https://scikit-learn.org/stable/whats_new/v1.0.html#version-1-0-0
Minimal dependencies

Version 1.0.0 of scikit-learn requires python 3.7+, numpy 1.14.6+ and scipy 1.1.0+. Optional minimal dependency is matplotlib 2.2.2+.

**Comment by FloHauss** [comment]
Notizen für eventuelle Followup Email: 
- Ist der workaround das LF_data flag einmal zu setzen, um die npz-Matrizen zu generieren valide?
- Falls ja, warum wird dann der Fehler geworfen, dass alle input-arrays dieselbe Dimensionen haben müssen?

**Comment by leon-me** [comment]
To Do: Diff der Files aus Dropbox und dem Github Repo machen
