### ISSUE TITLE
Paper ToDos

### ISSUE THREAD

**Issue by leon-me** [FloHauss/XMC_HTC#6]
Hier können wir sammeln, was im Paper noch zu tun ist. Jeder schreibt einfach die Punkte, die er noch offen hat, rein.

- [x] #10
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #22 
- [ ] 2.2 Zitationen in der Einleitung --> David

**Comment by NeriBert** [comment]
- [ ] 1 & 4.5 Aktualisierung von Einleitung & Metriken

**Comment by FloHauss** [comment]
- 2.2 XR-Transformer Abschnitt präzisieren 
- 2.2 Zitationen in der Einleitung

**Comment by FloHauss** [comment]
- Introduction reviewen

**Comment by leon-me** [comment]
closing in favour of milestone and separate issues
